name: Build and Push Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: docker.io
  IMAGE_NAME: donchev7/catvton

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"

      - name: Configure Docker to use LVM volume
        run: |
          # Stop all Docker services
          sudo systemctl stop docker.socket docker.service

          # Clean up any existing Docker data
          sudo rm -rf /home/runner/work/catvton-flux/catvton-flux/docker

          # Create Docker daemon config directory if it doesn't exist
          sudo mkdir -p /etc/docker

          # Create or update daemon.json
          sudo tee /etc/docker/daemon.json << EOF
          {
            "data-root": "/home/runner/work/catvton-flux/catvton-flux/docker"
          }
          EOF

          # Start Docker service
          sudo systemctl start docker.socket docker.service

          # Verify Docker is using the new location
          docker info | grep "Docker Root Dir"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: donchev7
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=long

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            HF_TOKEN=${{ secrets.HF_SECRET }}
