name: Build and Push Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: docker.io
  IMAGE_NAME: donchev7/catvton

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Configure Docker to use LVM volume
        run: |
          echo "=== Disk Usage ==="
          df -h

          echo -e "\n=== Top 10 Largest Directories in / ==="
          sudo du -h / --max-depth=1 2>/dev/null | sort -hr | head -n 10

          echo -e "\n=== Top 10 Largest Directories in /usr ==="
          sudo du -h /usr --max-depth=1 2>/dev/null | sort -hr | head -n 10

          echo -e "\n=== Top 10 Largest Directories in /var ==="
          sudo du -h /var --max-depth=1 2>/dev/null | sort -hr | head -n 10

          echo -e "\n=== Top 10 Largest Directories in /opt ==="
          sudo du -h /opt --max-depth=1 2>/dev/null | sort -hr | head -n 10

          echo -e "\n=== Docker Related Directories ==="
          sudo du -h /var/lib/docker 2>/dev/null || true
          sudo du -h /mnt/docker 2>/dev/null || true

          # Stop all Docker services
          sudo systemctl stop docker.socket docker.service

          # Clean up old Docker data
          sudo rm -rf /var/lib/docker
          sudo rm -rf /mnt/docker

          # Create new Docker directory with proper permissions
          sudo mkdir -p /mnt/docker
          sudo chown -R root:root /mnt/docker
          sudo chmod 711 /mnt/docker

          # Create Docker daemon config directory if it doesn't exist
          sudo mkdir -p /etc/docker

          # Create or update daemon.json
          sudo tee /etc/docker/daemon.json << EOF
          {
            "data-root": "/mnt/docker"
          }
          EOF

          # Start Docker service
          sudo systemctl start docker.socket docker.service

          # Verify Docker is using the new location and show available space
          echo "=== Docker Root Directory ==="
          docker info | grep "Docker Root Dir"
          echo "=== Available Space in Docker Root ==="
          df -h /mnt/docker

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: donchev7
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=long

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            HF_TOKEN=${{ secrets.HF_SECRET }}
